spring:
  datasource:
    jdbcUrl: ${BATCH_DATASOURCE_URL:jdbc:mysql://localhost:3306/spring_batch}
    username: ${BATCH_USERNAME:root}
    password: ${BATCH_PASSWORD:root}
  batch:
    jdbc:
      initialize-schema: "always"

app:
  datasource:
    jdbcUrl: ${APP_DATASOURCE_URL:jdbc:mysql://localhost:3306/app}
    username: ${APP_USERNAME:root}
    password: ${APP_PASSWORD:root}

logging:
  config: /etc/config/primeirojobspringbatch/log4j.xml
